server:
  port: 8282
management:
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: "*"
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/springboot_tutorial
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl